music/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'music'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^album/add/$', views.AlbumCreate.as_view(), name='album-add')
]

website/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),  
    url(r'^music/', include('music.urls'))
]

music/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Album(models.Model):
	artist = models.CharField(max_length=250)
	album_title = models.CharField(max_length=500)
	genere = models.CharField(max_length=100)
	album_logo = models.CharField(max_length=1000)

	def get_absolute_url(self):
		return reverse ('music:detail', kwargs={'pk': self.pk})

	def __str__(self):
		return self.album_title + ' ' + self.artist
	
class Song(models.Model):
	album  = models.ForeignKey(Album, on_delete=models.CASCADE)
	file_type = models.CharField(max_length=100)
	song_title = models.CharField(max_length=250)
	is_favorite = models.BooleanField(default=False)
 
	def __str__(self):
		return self.song_title

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Album, Song

class IndexView(generic.ListView):
	"""docstring for IndexView"""
	template_name = 'music/index.html'
	context_object_name = "all_album"
	def get_queryset(self):
		return Album.objects.all()


class DetailView(generic.DetailView):
	"""docstring for DetailView"""
	model = Album
	template_name = 'music/detailPage.html'






class AlbumCreate(CreateView):
	"""docstring for AlbumCreate"""
	model = Album
	fields = ['artist', 'album_title', 'genere']
		

music/templates/music/album_form.html
{{% extends 'music/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Album</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form_template.html' %} 
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}}

music/templates/music/base.html
<!DOCTYPE html>
<html>
<head>
<title>{% block title %}Viberr{% endblock %}</title>
	{% load staticfiles%}
 <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>
<body>
  <nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<!-- -header -->
		<div class="navbar-header">
		    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
		    	<span class="icon-bar"></span>
		    	<span class="icon-bar"></span>
		    	<span class="icon-bar"></span>
		    </button>
			<a class = "navbar-brand" href="{% url 'music:index' %}">Viber</a>
		</div>


		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li class="active">
					<a href="{% url 'music:index' %}">
						<span class="glyphicon glyphicon-cd"></span>&nbsp Albums
					</a>
				</li>
				<li class="">
					<a href="{% url 'music:index' %}">
						<span class="glyphicon glyphicon-music"></span>&nbsp Songs
					</a>
				</li>
				<li class="">
					<a href="{% url 'music:index' %}">
						<span class="glyphicon glyphicon-music"></span>
					</a>
				</li>
			</ul>

			<form class="navbar-form navbar-left" role="search" method="get" action="#">
				<div class="form-group">
					<input type="text" class="form-control" name="q" value="">
				</div>
				<button type="submit" class="btn btn-default"> search</button>
			</form>


             <ul class="nav navbar-nav navbar-right">
				<li class="active">
					<a href="{% url 'music:album-add' %}">
						<span class="glyphicon glyphicon-plus"></span>&nbsp add Albums
					</a>
				</li>

				<li class="">
					<a href="{% url 'music:index' %}">
						<span class="glyphicon glyphicon-music"></span>&nbsp logout
					</a>
				</li>
			</ul>

		</div>
	</div>
</nav>
{% block body %}
{% endblock%}
</body>
</html>

music/templates/music/detailPage.html
{% extends "music/base.html" %}
{% block title %}
  detail Page
{% endblock %}

{% block body %}
<h1>{{album.album_title}}</h1>
<img src={{album.album_logo}} height="300" />
<h2>{{album.artist}}</h2>
<h3>{{album.genere}}</h3>


{% if error_message %}
  <p><strong>{{error_message}}</strong></p>
{% endif %}

<form action=  {% url 'music:favorite' album.id %} method="post">
	{% csrf_token %}
	{% for song in album.song_set.all %}
	<input type="radio" id="song{{ forloop.counter}}" name="song" value="{{song.id}}">
	<label for=""song{{ forloop.counter}}"">
				{{song.song_title}}
				{% if song.is_favorite %}
					<img src="http://www.clker.com/cliparts/O/Z/4/Q/W/Q/favourite-md.png" height="50" width="50" />
				{% endif %}
	</label><br />
	{% endfor %}
	<input  type="submit" value="favorite" />
</form>
{% endblock%}

music/templates/music/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

music/templates/music/index.html
{% extends "music/base.html" %}

{% block body %}

	<ul>
	    <h1>all my albums</h1 >
		{% for album in all_album %}
			<li><a href= "{% url 'music:detail' album.id %}">
				{{album.album_title}}</a>
			</li>
		{% endfor %}
	</ul>

{% endblock%}